### PR TITLE
fix: use `useId` instead of `useUUID`

### LINKED ISSUE #1790: fix: useId to generate id instead of getUUID
Since react 18 has a hook for generating IDs we can directly use it instead of using `getUUID` helper. Helper should also be removed.

### PR DESCRIPTION
**Pull request by QuiiBz**
## Summary

Closes #1790

## Type

- Refactor

#### What is expected?

Use React 18 `useId` hook instead of `useUUID`.
Remove the exports from index of `useUUID` and `getUUID`.
I could not delete `getUUID` because it's still used in places where we can't use `useId`

### CODE REVIEW

File: src/utils/ids.ts [hunk 1]
```diff
@@ -1,9 +1,5 @@
-import { useMemo } from 'react'
-
 const chr4 = () => Math.random().toString(16).slice(-4)
 const uuid = () => Array.from({ length: 8 }, chr4).join('')
 
 export const getUUID = (prefix = ''): string =>
   `${prefix ? `${prefix}-` : ''}${uuid()}`
```
Comment (matthprost) [inline src/utils/ids.ts:5]: To remove ?

File: src/utils/ids.ts [hunk 2]
```diff
@@ -1,9 +1,5 @@
-import { useMemo } from 'react'
-
 const chr4 = () => Math.random().toString(16).slice(-4)
 const uuid = () => Array.from({ length: 8 }, chr4).join('')
```
Comment (matthprost) [inline src/utils/ids.ts:2]: Maybe all the file actually

**Review by matthprost — CHANGES_REQUESTED** [review]

File: src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap [hunk 3]
```diff
@@ -2111,7 +2111,7 @@ exports[`SelectableCard renders correctly with radio type and tooltip prop 1`] =
 }
 
 <div
-    aria-describedby="tooltip-6c756c756c756c756c756c756c756c75"
+    aria-describedby=":rl:"
```
Comment (matthprost) [inline src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap:2114]: is that the normal format of id ??

**Review by matthprost — CHANGES_REQUESTED** [review]

File: src/utils/ids.ts (hunk 2 above)
Comment (QuiiBz) [reply src/utils/ids.ts:2]: From the PR description:

> I could not delete `getUUID` because it's still used in places where we can't use `useId`

File: src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap (hunk 3 above)
Comment (QuiiBz) [reply src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap:2114]: Yes

**Review by matthprost — APPROVED** [review]
